### ISSUE TITLE
uvicorn missing in requirements

### ISSUE THREAD

**Issue by arne-cl** [almarklein/timetagger#18]
Hi Almar,
after installing timetagger (`pip install -r requirements.txt && python setup.py install`),
I get this error:

```
(timetagger) arne@t470:~/repos/timetagger$ python run.py
[INFO 2021-01-14 12:00:29] Compiled pscript from dialogs.py
[INFO 2021-01-14 12:00:29] Compiled pscript from front.py
[INFO 2021-01-14 12:00:29] Compiled pscript from dt.py
[INFO 2021-01-14 12:00:29] Compiled pscript from auth.py
[INFO 2021-01-14 12:00:29] Compiled pscript from stores.py
[INFO 2021-01-14 12:00:29] Compiled pscript from utils.py
[INFO 2021-01-14 12:00:29] Collected 11 assets from /home/arne/repos/timetagger/timetagger/client/.
[INFO 2021-01-14 12:00:29] Collected 9 assets from /home/arne/repos/timetagger/timetagger/static/.
[INFO 2021-01-14 12:00:29] Collected 13 assets from /home/arne/repos/timetagger/timetagger/images/.
Traceback (most recent call last):
  File "run.py", line 51, in <module>
    asgineer.run(main_handler, "uvicorn", "0.0.0.0:80", log_level="warning")
  File "/home/arne/.virtualenvs/timetagger/lib/python3.7/site-packages/asgineer/_run.py", line 39, in run
    return func(appname, bind, **kwargs)
  File "/home/arne/.virtualenvs/timetagger/lib/python3.7/site-packages/asgineer/_run.py", line 55, in _run_uvicorn
    from uvicorn.main import main
ModuleNotFoundError: No module named 'uvicorn'
```

**Comment by almarklein** [comment]
Closed by #19 

Thanks, I think I've missed that one because the test don't actually need it :)
